const RESEND_COOLDOWN_SECONDS = 30
const RESEND_COOLDOWN_NETWORK_GRACE_TIME = 2 // time substracted from cooldown ttl to account for network time between client and server
const OTP_TTL_SECONDS = 60 * 5
const OTP_VERIFICATION_ATTEMPTS_TTL_SECONDS = 60 * 60 * 24
const OTP_VERIFICATIONS_BEFORE_COOLDOWNS = 5
const OTP_VERIFICATION_COOLDOWN_SECONDS = 30

const otpConstants = {
	RESEND_COOLDOWN_SECONDS,
	RESEND_COOLDOWN_NETWORK_GRACE_TIME,
	OTP_TTL_SECONDS,
	OTP_VERIFICATION_ATTEMPTS_TTL_SECONDS,
	OTP_VERIFICATIONS_BEFORE_COOLDOWNS,
	OTP_VERIFICATION_COOLDOWN_SECONDS,
}

export default otpConstants
